---
- name: Check whether Cureutils command is installed
  ansible.builtin.command: cure version
  register: cureutils_installed
  ignore_errors: yes
  changed_when: false
  environment:
    RUBYOPT: -EUTF-8
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install Bundler
  community.general.gem:
    name: bundler
    state: latest
    user_install: no
  when: cureutils_installed is failed

- name: Update gem
  ansible.builtin.command: gem update --system
  ignore_errors: yes
  when: cureutils_installed is failed

- name: Install Cureutils
  community.general.gem:
    name: cureutils
    state: present
    user_install: no
  when: cureutils_installed is failed
