---
- name: Check whether Cureutils command is installed
  command: cure version
  register: CUREUTILS_INSTALLED
  ignore_errors: yes
  changed_when: false
  environment:
    RUBYOPT: -EUTF-8
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install Bundler
  gem:
    name: bundler
    state: latest
    user_install: no
  when: CUREUTILS_INSTALLED is failed

- name: Update gem
  shell: gem update --system
  ignore_errors: yes
  when: CUREUTILS_INSTALLED is failed

- name: Install Cureutils
  gem:
    name: cureutils
    state: present
    user_install: no
  when: CUREUTILS_INSTALLED is failed
