---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether Cureutils is installed
      command: cure version
      register: CURE_VERSION
      changed_when: false
      environment:
        RUBYOPT: -EUTF-8
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Check OS version
      command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure Cureutils is installed
      debug:
        var: CURE_VERSION

    - name: Show OS version
      debug:
        var: OS_VERSION
