---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether Cureutils is installed
      ansible.builtin.command: cure version
      register: cure_version
      changed_when: false
      environment:
        RUBYOPT: -EUTF-8
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure Cureutils is installed
      ansible.builtin.debug:
        var: cure_version

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
